"""
@UnrealClaude Script
@Description: Create M_PoisonCircle_PP post-process material for poison circle darkening effect
"""
import unreal
mpc = unreal.load_asset('/Game/GamePlay/Materials/MPC_PoisonCircle')
asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
factory = unreal.MaterialFactoryNew()
material = asset_tools.create_asset('M_PoisonCircle_PP', '/Game/GamePlay/Materials/', unreal.Material, factory)
material.set_editor_property('material_domain', unreal.MaterialDomain.MD_POST_PROCESS)
material.set_editor_property('blendable_location', unreal.BlendableLocation.BL_AFTER_TONEMAPPING)
editor = unreal.MaterialEditingLibrary
# Nodes
n_center = editor.create_material_expression(material, unreal.MaterialExpressionCollectionParameter, -800, 0)
n_center.set_editor_property('collection', mpc)
n_center.set_editor_property('parameter_name', 'CircleCenter')
n_radius = editor.create_material_expression(material, unreal.MaterialExpressionCollectionParameter, -800, 200)
n_radius.set_editor_property('collection', mpc)
n_radius.set_editor_property('parameter_name', 'CircleRadius')
n_soft = editor.create_material_expression(material, unreal.MaterialExpressionCollectionParameter, -800, 400)
n_soft.set_editor_property('collection', mpc)
n_soft.set_editor_property('parameter_name', 'EdgeSoftness')
n_wp = editor.create_material_expression(material, unreal.MaterialExpressionWorldPosition, -500, 0)
n_mwp = editor.create_material_expression(material, unreal.MaterialExpressionComponentMask, -300, 0)
n_mwp.set_editor_property('r', True)
n_mwp.set_editor_property('g', True)
n_mwp.set_editor_property('b', False)
n_mwp.set_editor_property('a', False)
n_mc = editor.create_material_expression(material, unreal.MaterialExpressionComponentMask, -300, 150)
n_mc.set_editor_property('r', True)
n_mc.set_editor_property('g', True)
n_mc.set_editor_property('b', False)
n_mc.set_editor_property('a', False)
n_dist = editor.create_material_expression(material, unreal.MaterialExpressionDistance, -100, 50)
n_sub = editor.create_material_expression(material, unreal.MaterialExpressionSubtract, 100, 50)
n_div = editor.create_material_expression(material, unreal.MaterialExpressionDivide, 300, 50)
n_sat = editor.create_material_expression(material, unreal.MaterialExpressionSaturate, 500, 50)
n_scene = editor.create_material_expression(material, unreal.MaterialExpressionSceneTexture, 500, 300)
n_scene.set_editor_property('scene_texture_id', unreal.SceneTextureId.PPI_POST_PROCESS_INPUT0)
n_mul = editor.create_material_expression(material, unreal.MaterialExpressionMultiply, 700, 300)
n_mul.set_editor_property('const_b', 0.3)
n_lerp = editor.create_material_expression(material, unreal.MaterialExpressionLinearInterpolate, 900, 150)
# Connections
editor.connect_material_expressions(n_wp, '', n_mwp, '')
editor.connect_material_expressions(n_center, '', n_mc, '')
editor.connect_material_expressions(n_mwp, '', n_dist, 'A')
editor.connect_material_expressions(n_mc, '', n_dist, 'B')
editor.connect_material_expressions(n_dist, '', n_sub, 'A')
editor.connect_material_expressions(n_radius, '', n_sub, 'B')
editor.connect_material_expressions(n_sub, '', n_div, 'A')
editor.connect_material_expressions(n_soft, '', n_div, 'B')
editor.connect_material_expressions(n_div, '', n_sat, '')
editor.connect_material_expressions(n_scene, '', n_mul, 'A')
editor.connect_material_expressions(n_scene, '', n_lerp, 'A')
editor.connect_material_expressions(n_mul, '', n_lerp, 'B')
editor.connect_material_expressions(n_sat, '', n_lerp, 'Alpha')
editor.connect_material_property(n_lerp, '', unreal.MaterialProperty.MP_EMISSIVE_COLOR)
unreal.EditorAssetLibrary.save_loaded_asset(material)
unreal.log('Material M_PoisonCircle_PP created!')